### ISSUE TITLE
exclude paths from prepend

### ISSUE THREAD

**Issue by surendra-iouring** [iouring-engineering/openapi-merge#10]
An existing prepend feature is great option for adding some basic path in all the API's however in our case we may have to ignore some of paths from adding prepend paths, can we have any solution for this?

**Comment by revanth-iouring** [comment]
@surendra-iouring Thanks for bringing this feature, we Created pull request for this [https://github.com/iouring-engineering/openapi-merge/pull/11](https://github.com/iouring-engineering/openapi-merge/pull/11)
