### ISSUE TITLE
Title should be configurable through openapi-merge.json

### ISSUE THREAD

**Issue by santhosh-iouring** [iouring-engineering/openapi-merge#5]
#### Open API Title:
While merging multiple openapi 3.0 files using the tool @iouring-engineering/openapi-merge-cli, the title of the final output file is copied from the first input file mentioned in openapi-merge.json. Title reference attached here,

![openapititle](https://user-images.githubusercontent.com/103554827/164397705-56eb61ff-525b-437a-a170-ec834a512fec.JPG)

Since we are merging multiple micro service units to a single file, the title of the document will vary for each service stack
It should be really helpful if title can be configurable through openapi-merge.json.

**Comment by revanth-iouring** [comment]
@santhosh-iouring As you requested, changes has been made and merged into library [PR](https://github.com/iouring-engineering/openapi-merge/pull/6), also released a new version [1.3.9](https://www.npmjs.com/package/@iouring-engineering/openapi-merge-cli/v/1.3.9) , requesting you to verify and let us know if any changes are required.
